In [37]:
!git clone https://github.com/Ethereal1z/DRMGNE.git

fatal: destination path 'DRMGNE' already exists and is not an empty directory.

In [38]:
import pandas as pd
import os
from IPython.display import display

DATA_DIR = '/content/DRMGNE/data/B-dataset'
files_to_check = [
    "DiseaseGIP.csv", "DiseasePS.csv", "DrugDiseaseAssociationNumber.csv",
    "DrugFingerprint.csv", "DrugGIP.csv", "DrugID.csv", "DrugInformation.csv",
    "DrugProteinAssociationNumber.csv", "ProteinDiseaseAssociationNumber.csv",
    "ProteinGIP_Disease.csv", "ProteinGIP_Drug.csv", "ProteinID.csv",
    "ProteinInformation.csv", "Protein_sequence.csv", "adj.csv", "diseaseName.csv"
]

for file_name in files_to_check:
    file_path = os.path.join(DATA_DIR, file_name)

    if os.path.exists(file_path):
        print(f"====== {file_name} ======")
        try:
            df = pd.read_csv(file_path, header=None)

            print(f"Shape: {df.shape} (Rows, Columns)")
            display(df.head(1))

        except pd.errors.EmptyDataError:
            print("File is empty.")
        except Exception as e:
            print(f"Error reading file: {e}")
        print("\n")
    else:
        print(f"File not found: {file_name}\n")

====== DiseaseGIP.csv ======
Shape: (599, 599) (Rows, Columns)

,0,1,2,3,4,5,6,7,8,9,...,589,590,591,592,593,594,595,596,597,598
0,NaN,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,588.0,589.0,590.0,591.0,592.0,593.0,594.0,595.0,596.0,597.0

====== DiseasePS.csv ======
Shape: (599, 599) (Rows, Columns)

,0,1,2,3,4,5,6,7,8,9,...,589,590,591,592,593,594,595,596,597,598
0,NaN,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,588.0,589.0,590.0,591.0,592.0,593.0,594.0,595.0,596.0,597.0

====== DrugDiseaseAssociationNumber.csv ======
Shape: (18411, 2) (Rows, Columns)

      0        1
0  drug  disease

====== DrugFingerprint.csv ======
Shape: (270, 270) (Rows, Columns)

,0,1,2,3,4,5,6,7,8,9,...,260,261,262,263,264,265,266,267,268,269
0,NaN,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,259.0,260.0,261.0,262.0,263.0,264.0,265.0,266.0,267.0,268.0

====== DrugGIP.csv ======
Shape: (270, 270) (Rows, Columns)

,0,1,2,3,4,5,6,7,8,9,...,260,261,262,263,264,265,266,267,268,269
0,NaN,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,259.0,260.0,261.0,262.0,263.0,264.0,265.0,266.0,267.0,268.0

====== DrugID.csv ======
Shape: (270, 1) (Rows, Columns)

    0
0  id

====== DrugInformation.csv ======
Shape: (270, 3) (Rows, Columns)

      0   1       2
0  name  id  smiles

====== DrugProteinAssociationNumber.csv ======
Shape: (3111, 2) (Rows, Columns)

      0        1
0  drug  protein

====== ProteinDiseaseAssociationNumber.csv ======
Shape: (5899, 2) (Rows, Columns)

         0        1
0  disease  protein

====== ProteinGIP_Disease.csv ======
Shape: (1022, 1022) (Rows, Columns)

,0,1,2,3,4,5,6,7,8,9,...,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021
0,NaN,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,1011.0,1012.0,1013.0,1014.0,1015.0,1016.0,1017.0,1018.0,1019.0,1020.0

====== ProteinGIP_Drug.csv ======
Shape: (1022, 1022) (Rows, Columns)

,0,1,2,3,4,5,6,7,8,9,...,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021
0,NaN,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,1011.0,1012.0,1013.0,1014.0,1015.0,1016.0,1017.0,1018.0,1019.0,1020.0

====== ProteinID.csv ======
Shape: (1022, 1) (Rows, Columns)

    0
0  id

====== ProteinInformation.csv ======
Shape: (1022, 2) (Rows, Columns)

    0         1
0  id  sequence

====== Protein_sequence.csv ======
Shape: (1022, 1022) (Rows, Columns)

,0,1,2,3,4,5,6,7,8,9,...,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021
0,NaN,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,...,1011.0,1012.0,1013.0,1014.0,1015.0,1016.0,1017.0,1018.0,1019.0,1020.0

====== adj.csv ======
Shape: (270, 599) (Rows, Columns)

,0,1,2,3,4,5,6,7,8,9,...,589,590,591,592,593,594,595,596,597,598
0,NaN,0,1,2,3,4,5,6,7,8,...,588,589,590,591,592,593,594,595,596,597

====== diseaseName.csv ======
Shape: (598, 2) (Rows, Columns)

      0                  1
0  1025  anxiety disorders

In [39]:
"""
Central config for the MPHAM reproduction.

Every field that the paper LEAVES UNSPECIFIED is exposed here as an explicit
knob, so you can ablate the inferred choices instead of having them buried in
code. Defaults are set to "paper-faithful where stated, sane where inferred".
Fields whose value is a guess are marked  # INFERRED.
"""
from dataclasses import dataclass, field
from typing import Dict, List


# ---- B-dataset (protein-augmented) cardinalities, derived from your CSVs ----
N_DRUG = 269
N_DIS = 598
N_PROT = 1021
N_TOTAL = N_DRUG + N_DIS + N_PROT  # 1888


@dataclass
class Config:
    # ---------- data ----------
    data_dir: str = "/content/DRMGNE/data/B-dataset"            # folder holding the B-dataset csvs
    n_drug: int = N_DRUG
    n_dis: int = N_DIS
    n_prot: int = N_PROT

    # Similarity fusion for the diagonal blocks of H0 (S_rr, S_dd, S_pp).
    # The paper never says how fingerprint/PS/sequence and GIP are combined.
    # "mean"      -> elementwise mean of the available similarity sources
    # "gip_fill"  -> use structural sim where it is >0, else fall back to GIP
    # "gip_only"  -> GIP kernel only
    # "struct_only" -> structural sim only (fingerprint / PS / sequence)
    sim_fusion: str = "gip_fill"          # INFERRED

    # GIP kernels in your csvs are precomputed on the FULL association matrix.
    # That is label leakage under CV. recompute_gip=True rebuilds drug/disease
    # GIP per fold from TRAIN-ONLY drug-disease edges (honest). Set False to
    # reproduce the paper's (leaky) numbers.
    recompute_gip: bool = False      # INFERRED / leakage switch

    # Dense similarity matrices used directly as adjacency => every node attends
    # to ~all nodes => over-smoothing. Keep top-k neighbours per row instead.
    # Set sim_topk<=0 to disable (use all >sim_threshold).
    sim_topk: int = 50                # INFERRED (paper unspecified)
    sim_threshold: float = 0.0        # keep edges with weight > threshold

    # ---------- meta-paths ----------
    # distance (number of edges) -> list of meta-path strings over {R,D,P}.
    # These are a concrete instantiation of the (admittedly non-exhaustive) set
    # the paper enumerates in Sec II-C. Edit freely for ablations.
    metapaths: Dict[int, List[str]] = field(default_factory=lambda: {
        1: ["RR", "DD", "PP", "RD", "RP", "PD"],
        2: ["RPR", "RDR", "DPD", "RPD", "RDP"],
        3: ["RPDR", "RDPD", "RPRP"],
    })
    max_distance: int = 3             # paper: <=3 is enough

    # Binarise commuting matrices for the GAT neighbourhood (recommended).
    # If False, the raw (normalised) commuting weights are used as a non-attn
    # aggregation (Variant-2-like).
    binarize_adj: bool = True

    # ---------- model ----------
    emb_dim: int = 128                # paper sweeps {32,64,128,256}; 128/256 best
    n_layers: int = 1                 # INFERRED (paper: "layer l", L unspecified)
    dropout: float = 0.2              # INFERRED
    residual: bool = True             # INFERRED, fights over-smoothing
    layernorm: bool = True            # INFERRED, fights over-smoothing
    # Node-level attention form:
    #   "gat"   -> e_ij = LeakyReLU(a_src.Wh_i + a_dst.Wh_j)   (recommended)
    #   "paper" -> e_ij = a.Wh_j      (literal eq.4, j-only; weak, for ablation)
    node_attn: str = "paper"            # INFERRED reading of eq.4
    predictor_hidden: int = 128       # INFERRED

    # ---------- negative sampling ----------
    neg_ratio: int = 1                # train negatives per positive
    resample_neg_each_epoch: bool = True   # INFERRED but important
    # Negatives are drawn ONLY from pairs that are not positive in the FULL
    # matrix (so test positives are never used as train/test negatives twice).

    # ---------- training ----------
    lr: float = 1e-3
    weight_decay: float = 5e-4
    epochs: int = 200
    early_stop_patience: int = 200
    seed: int = 42

    # ---------- evaluation ----------
    n_folds: int = 5
    # "balanced"  -> test set = test positives + equal #random test negatives.
    #                This is almost certainly what the paper reports (AUPR~0.95).
    # "full"      -> all non-train-positive pairs are candidates (realistic,
    #                AUPR will be much lower). Report BOTH.
    eval_mode: str = "balanced"       # INFERRED, drives AUPR massively
    score_threshold: float = 0.5      # for Precision/Recall/F1 only

In [40]:
"""
B-dataset loader.

The csv previews you gave show a leading index column and a header row of
column indices, i.e. they were written with `DataFrame.to_csv(index=True)`.
`_read_matrix` strips that defensively and coerces to float. If your real files
differ, the asserts will tell you exactly where.

Matrices returned (all numpy float32):
    A_rd : (n_drug, n_dis)   drug-disease   (from adj.csv, the source of truth)
    A_rp : (n_drug, n_prot)  drug-protein
    A_pd : (n_prot, n_dis)   protein-disease
    S_rr : (n_drug, n_drug)  fused drug similarity
    S_dd : (n_dis,  n_dis)   fused disease similarity
    S_pp : (n_prot, n_prot)  fused protein similarity
"""
import os
import numpy as np
import pandas as pd

def _read_matrix(path, expected_shape=None):
    """Read a (possibly index+header) numeric matrix and return a float array."""
    df = pd.read_csv(path, header=0, index_col=0)
    # drop any all-NaN first column/row leftovers
    arr = df.apply(pd.to_numeric, errors="coerce").to_numpy(dtype=np.float64)
    if np.isnan(arr).any():
        # a stray NaN in [0,0] is the classic to_csv artefact; fill with 0
        arr = np.nan_to_num(arr, nan=0.0)
    if expected_shape is not None:
        assert arr.shape == expected_shape, (
            f"{os.path.basename(path)}: got {arr.shape}, expected {expected_shape}. "
            f"Adjust header/index_col in _read_matrix.")
    return arr.astype(np.float32)

def _read_pairs(path, max_col0, max_col1):
    df = pd.read_csv(path, header=0)
    pairs = df.to_numpy(dtype=np.int64)

    # 1. Fix 1-based indexing (if min value is 1, shift everything down by 1 to be 0-based)
    if pairs.min() >= 1:
        pairs = pairs - 1

    # 2. Fix swapped columns (if col 0 exceeds max_col0, they are likely flipped)
    if pairs[:, 0].max() >= max_col0 and pairs[:, 1].max() < max_col0:
        print(f"Auto-fixing swapped columns for: {os.path.basename(path)}")
        pairs = pairs[:, [1, 0]]

    # 3. Final validation
    assert pairs[:, 0].max() < max_col0 and pairs[:, 1].max() < max_col1, \
        f"{os.path.basename(path)}: indices out of range. Col0 max: {pairs[:, 0].max()}, Col1 max: {pairs[:, 1].max()}"

    return pairs

def _read_matrix(path, shape=None):
    df = pd.read_csv(path, header=0, index_col=0)          # label row + label col
    arr = df.apply(pd.to_numeric, errors="coerce").to_numpy(np.float64)
    arr = np.nan_to_num(arr, nan=0.0).astype(np.float32)
    if shape is not None:
        assert arr.shape == shape, f"{path}: got {arr.shape}, expected {shape}"
    return arr


def _topk_sparsify(S, k, thr):
    """Keep top-k off-diagonal neighbours per row above thr; zero the rest.
    Returns a symmetric (max) sparsified copy. Diagonal forced to 0."""
    S = S.copy()
    np.fill_diagonal(S, 0.0)
    if thr > 0:
        S[S <= thr] = 0.0
    if k and k > 0:
        n = S.shape[0]
        for i in range(n):
            row = S[i]
            if (row > 0).sum() > k:
                kth = np.partition(row, -k)[-k]
                row[row < kth] = 0.0
    S = np.maximum(S, S.T)  # symmetrise
    return S


def _fuse(sources, mode):
    sources = [s for s in sources if s is not None]
    if mode == "struct_only":
        return sources[0]
    if mode == "gip_only":
        return sources[-1]
    if mode == "gip_fill":
        base = sources[0].copy()
        gip = sources[-1]
        mask = base <= 0
        base[mask] = gip[mask]
        return base
    # "mean"
    return np.mean(np.stack(sources, 0), axis=0).astype(np.float32)


def gip_kernel(profiles):
    """Gaussian Interaction Profile kernel over rows of `profiles` (n, d_feat).
    gamma normalised by the mean squared norm of the profiles (Laarhoven 2011)."""
    sq = (profiles ** 2).sum(1)
    gamma = 1.0 / (sq.mean() + 1e-12)
    # ||pi-pj||^2 = sq_i + sq_j - 2 pi.pj
    G = sq[:, None] + sq[None, :] - 2.0 * profiles @ profiles.T
    np.clip(G, 0, None, out=G)
    return np.exp(-gamma * G).astype(np.float32)


class BDataset:
    def __init__(self, cfg: Config):
        self.cfg = cfg
        d = cfg.data_dir
        nR, nD, nP = cfg.n_drug, cfg.n_dis, cfg.n_prot

        # ----- associations -----
        self.A_rd = _read_matrix(os.path.join(d, "adj.csv"), (nR, nD))
        self.A_rd = (self.A_rd > 0).astype(np.float32)

        rp = _read_pairs(os.path.join(d, "DrugProteinAssociationNumber.csv"), nR, nP)
        self.A_rp = np.zeros((nR, nP), np.float32)
        self.A_rp[rp[:, 0], rp[:, 1]] = 1.0

        # NOTE: file columns are (disease, protein)
        pd_ = _read_pairs(os.path.join(d, "ProteinDiseaseAssociationNumber.csv"), nD, nP)
        self.A_pd = np.zeros((nP, nD), np.float32)
        self.A_pd[pd_[:, 1], pd_[:, 0]] = 1.0

        # ----- raw similarity sources -----
        self._drug_struct = _read_matrix(os.path.join(d, "DrugFingerprint.csv"), (nR, nR))
        self._drug_gip = _read_matrix(os.path.join(d, "DrugGIP.csv"), (nR, nR))
        self._dis_struct = _read_matrix(os.path.join(d, "DiseasePS.csv"), (nD, nD))
        self._dis_gip = _read_matrix(os.path.join(d, "DiseaseGIP.csv"), (nD, nD))
        self._prot_seq = _read_matrix(os.path.join(d, "Protein_sequence.csv"), (nP, nP))
        gip_drug = _read_matrix(os.path.join(d, "ProteinGIP_Drug.csv"), (nP, nP))
        gip_dis = _read_matrix(os.path.join(d, "ProteinGIP_Disease.csv"), (nP, nP))
        self._prot_gip = ((gip_drug + gip_dis) / 2.0).astype(np.float32)

    # similarity built per-fold so GIP can be recomputed leak-free
    def build_similarities(self, A_rd_train):
        cfg = self.cfg
        if cfg.recompute_gip:
            # GIP from train-only drug-disease interaction profiles
            drug_gip = gip_kernel(A_rd_train)            # (nR,nR) from drug profiles
            dis_gip = gip_kernel(A_rd_train.T)           # (nD,nD) from disease profiles
        else:
            drug_gip, dis_gip = self._drug_gip, self._dis_gip
        S_rr = _fuse([self._drug_struct, drug_gip], cfg.sim_fusion)
        S_dd = _fuse([self._dis_struct, dis_gip], cfg.sim_fusion)
        S_pp = _fuse([self._prot_seq, self._prot_gip], cfg.sim_fusion)
        S_rr = _topk_sparsify(S_rr, cfg.sim_topk, cfg.sim_threshold)
        S_dd = _topk_sparsify(S_dd, cfg.sim_topk, cfg.sim_threshold)
        S_pp = _topk_sparsify(S_pp, cfg.sim_topk, cfg.sim_threshold)
        return S_rr, S_dd, S_pp

    @property
    def positives(self):
        r, c = np.where(self.A_rd > 0)
        return np.stack([r, c], 1)


def sample_negatives(pos_set, n_neg, nR, nD, rng, forbid=None):
    """Uniformly sample n_neg (drug,disease) pairs absent from pos_set and
    from `forbid`. pos_set/forbid are sets of flattened keys (r*nD + d)."""
    forbid = forbid or set()
    out = []
    while len(out) < n_neg:
        r = rng.integers(0, nR, size=n_neg)
        d = rng.integers(0, nD, size=n_neg)
        for a, b in zip(r, d):
            key = int(a) * nD + int(b)
            if key in pos_set or key in forbid:
                continue
            out.append((a, b))
            if len(out) >= n_neg:
                break
    return np.array(out, dtype=np.int64)

In [41]:
"""
Builds (a) the H0 block feature matrix and (b) one NxN adjacency per meta-path,
grouped by distance. All numpy; train.py moves them to torch tensors.

Block order in the 1888-d node space:  [ drugs | diseases | proteins ].
"""
import numpy as np

def _slices(cfg: Config):
    nR, nD, nP = cfg.n_drug, cfg.n_dis, cfg.n_prot
    return slice(0, nR), slice(nR, nR + nD), slice(nR + nD, nR + nD + nP)


def build_H0(A_rd, A_rp, A_pd, S_rr, S_dd, S_pp):
    """Eq.(1): block matrix of similarities (diag) and associations (off-diag)."""
    nR, nD, nP = A_rd.shape[0], A_rd.shape[1], A_rp.shape[1]
    N = nR + nD + nP
    H0 = np.zeros((N, N), np.float32)
    r, d, p = slice(0, nR), slice(nR, nR + nD), slice(nR + nD, N)
    H0[r, r] = S_rr;            H0[r, d] = A_rd;      H0[r, p] = A_rp
    H0[d, r] = A_rd.T;          H0[d, d] = S_dd;      H0[d, p] = A_pd.T
    H0[p, r] = A_rp.T;          H0[p, d] = A_pd;      H0[p, p] = S_pp
    return H0


def _base_blocks(A_rd, A_rp, A_pd, S_rr, S_dd, S_pp):
    """Edge-type -> matrix lookup used to compose meta-paths."""
    return {
        "RR": S_rr, "DD": S_dd, "PP": S_pp,
        "RD": A_rd, "DR": A_rd.T,
        "RP": A_rp, "PR": A_rp.T,
        "PD": A_pd, "DP": A_pd.T,
    }


def _metapath_commuting(path, blocks):
    """Multiply consecutive edge blocks. 'RPD' -> RP @ PD  (drug x disease)."""
    mats = []
    for a, b in zip(path[:-1], path[1:]):
        mats.append(blocks[a + b])
    M = mats[0]
    for m in mats[1:]:
        M = M @ m
    return M  # shape: (count[path[0]], count[path[-1]])


def build_metapath_adjs(cfg, A_rd, A_rp, A_pd, S_rr, S_dd, S_pp):
    """Return {distance: [(name, NxN float adjacency), ...]}.

    Each meta-path commuting matrix is placed into the full NxN node space at
    the (start-type, end-type) block and symmetrised. Optionally binarised.
    Row-normalised so non-attention variants stay numerically stable.
    """
    nR, nD, nP = cfg.n_drug, cfg.n_dis, cfg.n_prot
    N = nR + nD + nP
    off = {"R": 0, "D": nR, "P": nR + nD}
    cnt = {"R": nR, "D": nD, "P": nP}
    blocks = _base_blocks(A_rd, A_rp, A_pd, S_rr, S_dd, S_pp)

    out = {}
    for dist, names in cfg.metapaths.items():
        if dist > cfg.max_distance:
            continue
        lst = []
        for name in names:
            M = _metapath_commuting(name, blocks)
            s_type, e_type = name[0], name[-1]
            A = np.zeros((N, N), np.float32)
            rs = slice(off[s_type], off[s_type] + cnt[s_type])
            cs = slice(off[e_type], off[e_type] + cnt[e_type])
            A[rs, cs] = M
            A = np.maximum(A, A.T)  # undirected
            if cfg.binarize_adj:
                A = (A > 0).astype(np.float32)
            else:
                deg = A.sum(1, keepdims=True)
                deg[deg == 0] = 1.0
                A = A / deg
            # np.fill_diagonal(A, 0.0)
            np.fill_diagonal(A, 1.0)
            lst.append((name, A))
        out[dist] = lst
    return out


def mask_test_edges(A_rd, test_pairs):
    """Remove test drug-disease positives so they leak into NEITHER H0 NOR any
    meta-path that traverses a drug-disease edge (RD, RDR, RPD, RPDR, RDPD...).
    This is THE leakage control. Returns a copy."""
    A = A_rd.copy()
    A[test_pairs[:, 0], test_pairs[:, 1]] = 0.0
    return A

In [42]:
"""
MPHAM model.

Three-level hierarchical attention per node, faithful to eqs (2)-(14):

  node-level     (eq 3-6) : GAT over neighbours within one meta-path
  pattern-level  (eq 7-9) : attention over meta-paths of the SAME distance k
  distance-level (eq 10-12): attention over distances k

Implemented densely (N=1888, NxN ~14MB/path) for clarity; switch to sparse if
you scale to Hetero-A (N~7800).
"""
import torch
import torch.nn as nn
import torch.nn.functional as F


NEG_INF = -9e15
# NEG_INF = -1e9

class MPHAMLayer(nn.Module):
    def __init__(self, in_dim, out_dim, n_distances, cfg):
        super().__init__()
        self.cfg = cfg
        # node-level (shared across meta-paths, eq.3 single W)
        self.node_W = nn.Linear(in_dim, out_dim, bias=False)
        self.a_src = nn.Parameter(torch.empty(out_dim))
        self.a_dst = nn.Parameter(torch.empty(out_dim))
        # pattern-level (eq.7) and distance-level (eq.10) transforms + contexts
        self.pat_lin = nn.Linear(out_dim, out_dim)
        self.u_a = nn.Parameter(torch.empty(out_dim))
        self.dist_lin = nn.Linear(out_dim, out_dim)
        self.u_b = nn.Parameter(torch.empty(out_dim))
        self.drop = nn.Dropout(cfg.dropout)
        self.norm = nn.LayerNorm(out_dim) if cfg.layernorm else nn.Identity()
        self.res_proj = (nn.Linear(in_dim, out_dim, bias=False)
                         if (cfg.residual and in_dim != out_dim) else None)
        self.reset_parameters()

    def reset_parameters(self):
        nn.init.xavier_uniform_(self.node_W.weight)  # eq: Xavier init
        nn.init.xavier_uniform_(self.pat_lin.weight)
        nn.init.xavier_uniform_(self.dist_lin.weight)
        for p in (self.a_src, self.a_dst, self.u_a, self.u_b):
            nn.init.normal_(p, std=0.1)
        if self.res_proj is not None:
            nn.init.xavier_uniform_(self.res_proj.weight)

    def _node_attention(self, Wh, adj):
        """GAT aggregation over one binary adjacency `adj` (N,N). Returns (N,d)."""
        if self.cfg.node_attn == "paper":          # literal eq.4: e_ij = a.Wh_j
            e_dst = Wh @ self.a_dst                  # (N,)
            scores = e_dst.unsqueeze(0).expand(adj.size(0), -1)
        else:                                        # standard GAT
            e_src = Wh @ self.a_src                  # (N,)
            e_dst = Wh @ self.a_dst                  # (N,)
            scores = e_src.unsqueeze(1) + e_dst.unsqueeze(0)
            scores = F.leaky_relu(scores, 0.2)
        scores = scores.masked_fill(adj == 0, NEG_INF)
        alpha = torch.softmax(scores, dim=1)
        # zero-out rows with no neighbours (softmax of all -inf -> nan)
        no_nb = (adj.sum(1, keepdim=True) == 0)
        alpha = torch.where(no_nb, torch.zeros_like(alpha), alpha)
        return alpha @ Wh

    def forward(self, H, adjs):
        Wh = F.relu(self.node_W(H))                  # eq.3
        Wh = self.drop(Wh)
        Hk_list = []
        for dist in sorted(adjs.keys()):
            Hkm = [self._node_attention(Wh, adj) for _, adj in adjs[dist]]
            # pattern-level attention (eq.7-9), per node, softmax over patterns
            U = [torch.tanh(self.pat_lin(h)) for h in Hkm]     # each (N,d)
            s = torch.stack([u @ self.u_a for u in U], dim=1)  # (N, M)
            beta = torch.softmax(s, dim=1)
            Hk = sum(beta[:, m:m + 1] * Hkm[m] for m in range(len(Hkm)))
            Hk_list.append(Hk)
        # distance-level attention (eq.10-12), softmax over distances
        Ud = [torch.tanh(self.dist_lin(h)) for h in Hk_list]
        sd = torch.stack([u @ self.u_b for u in Ud], dim=1)    # (N, K)
        gamma = torch.softmax(sd, dim=1)
        out = sum(gamma[:, k:k + 1] * Hk_list[k] for k in range(len(Hk_list)))
        # residual + norm (INFERRED; helps over-smoothing on the dense 11% graph)
        if self.cfg.residual:
            res = H if self.res_proj is None else self.res_proj(H)
            out = out + res
        out = self.norm(out)
        return out


class MPHAM(nn.Module):
    def __init__(self, cfg, in_dim, n_distances):
        super().__init__()
        self.cfg = cfg
        self.W_drug = nn.Linear(in_dim, cfg.emb_dim)
        self.W_dis = nn.Linear(in_dim, cfg.emb_dim)
        self.W_prot = nn.Linear(in_dim, cfg.emb_dim)
        dims = [in_dim] + [cfg.emb_dim] * cfg.n_layers
        # dims = [cfg.emb_dim] * (cfg.n_layers + 1)
        self.layers = nn.ModuleList([
            MPHAMLayer(dims[i], dims[i + 1], n_distances, cfg)
            for i in range(cfg.n_layers)
        ])

        # predictor (eq.14): concat drug & disease embeddings -> MLP -> logit
        self.predictor = nn.Sequential(
            nn.Linear(2 * cfg.emb_dim, cfg.predictor_hidden),
            nn.ReLU(),
            nn.Dropout(cfg.dropout),
            nn.Linear(cfg.predictor_hidden, 1),
        )


    def encode(self, H0, adjs):
        H = H0
        for layer in self.layers:
            H = layer(H, adjs)
        return H                                     # (N, d), eq.13 stacked



    # def encode(self, H0, adjs):
    #     nR, nD, nP = self.cfg.n_drug, self.cfg.n_dis, self.cfg.n_prot
    #     # Project node types independently
    #     h_drug = self.W_drug(H0[:nR])
    #     h_dis = self.W_dis(H0[nR:nR+nD])
    #     h_prot = self.W_prot(H0[nR+nD:])
    #     H = torch.cat([h_drug, h_dis, h_prot], dim=0)

    #     for layer in self.layers:
    #         H = layer(H, adjs)
    #     return H

    def score(self, H, drug_idx, dis_idx):
        nR = self.cfg.n_drug
        hr = H[drug_idx]
        hd = H[nR + dis_idx]
        return self.predictor(torch.cat([hr, hd], dim=1)).squeeze(-1)  # logits

In [43]:
"""
5-fold CV training harness with explicit leakage control.

Per fold:
  1. split positives into train/test
  2. mask test positives out of A_rd  -> rebuild H0 AND every meta-path adj
     (this is the single most important correctness step)
  3. (optional) recompute GIP from train-only A_rd
  4. transductive forward over the whole graph; BCE on train pairs with fresh
     negatives each epoch
  5. evaluate on test positives + matched negatives (balanced) or full matrix
"""
import numpy as np
import torch
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score, average_precision_score, precision_score, recall_score, f1_score

def _adjs_to_torch(adjs, device):
    return {k: [(n, torch.from_numpy(a).to(device)) for n, a in v]
            for k, v in adjs.items()}


def run_fold(cfg, ds, train_pos, test_pos, device, rng):
    nR, nD = cfg.n_drug, cfg.n_dis
    pos_set = set((ds.positives[:, 0] * nD + ds.positives[:, 1]).tolist())

    # ---- leakage control: mask test edges everywhere ----
    A_rd_tr = mask_test_edges(ds.A_rd, test_pos)
    S_rr, S_dd, S_pp = ds.build_similarities(A_rd_tr)
    H0 = build_H0(A_rd_tr, ds.A_rp, ds.A_pd, S_rr, S_dd, S_pp)
    adjs = build_metapath_adjs(cfg, A_rd_tr, ds.A_rp, ds.A_pd, S_rr, S_dd, S_pp)

    H0 = torch.from_numpy(H0).to(device)
    adjs = _adjs_to_torch(adjs, device)
    n_dist = len(adjs)

    model = MPHAM(cfg, in_dim=H0.shape[1], n_distances=n_dist).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=cfg.lr,
                           weight_decay=cfg.weight_decay)

    # fixed test negatives (balanced eval)
    test_neg = sample_negatives(pos_set, len(test_pos) * cfg.neg_ratio,
                                nR, nD, rng)
    test_neg_set = set((test_neg[:, 0] * nD + test_neg[:, 1]).tolist())

    best_auc, best_state, patience = -1, None, 0
    for epoch in range(cfg.epochs):
        model.train()
        if epoch == 0 or cfg.resample_neg_each_epoch:
            tr_neg = sample_negatives(pos_set, len(train_pos) * cfg.neg_ratio,
                                      nR, nD, rng, forbid=test_neg_set)
        pairs = np.concatenate([train_pos, tr_neg], 0)
        labels = np.concatenate([np.ones(len(train_pos)),
                                 np.zeros(len(tr_neg))]).astype(np.float32)
        di = torch.from_numpy(pairs[:, 0]).to(device)
        si = torch.from_numpy(pairs[:, 1]).to(device)
        y = torch.from_numpy(labels).to(device)

        opt.zero_grad()
        H = model.encode(H0, adjs)
        logits = model.score(H, di, si)
        loss = F.binary_cross_entropy_with_logits(logits, y)  # eq.15
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        opt.step()

        # validate on the held-out fold (balanced)
        auc, *_ = evaluate(cfg, model, H0, adjs, test_pos, test_neg, device)
        if auc > best_auc:
            best_auc, patience = auc, 0
            best_state = {k: v.detach().clone() for k, v in model.state_dict().items()}
        else:
            patience += 1
            if patience >= cfg.early_stop_patience:
                break

    model.load_state_dict(best_state)
    if cfg.eval_mode == "full":
        return evaluate_full(cfg, model, H0, adjs, test_pos, pos_set, train_pos, device)
    return evaluate(cfg, model, H0, adjs, test_pos, test_neg, device)


@torch.no_grad()
def evaluate(cfg, model, H0, adjs, test_pos, test_neg, device):
    model.eval()
    H = model.encode(H0, adjs)
    pairs = np.concatenate([test_pos, test_neg], 0)
    y = np.concatenate([np.ones(len(test_pos)), np.zeros(len(test_neg))])
    di = torch.from_numpy(pairs[:, 0]).to(device)
    si = torch.from_numpy(pairs[:, 1]).to(device)
    prob = torch.sigmoid(model.score(H, di, si)).cpu().numpy()
    return _metrics(y, prob, cfg.score_threshold)


@torch.no_grad()
def evaluate_full(cfg, model, H0, adjs, test_pos, pos_set, train_pos, device):
    """Realistic eval: every pair that is not a TRAIN positive is a candidate."""
    model.eval()
    H = model.encode(H0, adjs)
    nR, nD = cfg.n_drug, cfg.n_dis
    train_set = set((train_pos[:, 0] * nD + train_pos[:, 1]).tolist())
    test_set = set((test_pos[:, 0] * nD + test_pos[:, 1]).tolist())
    di, si, y = [], [], []
    for r in range(nR):
        for d in range(nD):
            key = r * nD + d
            if key in train_set:
                continue
            di.append(r); si.append(d); y.append(1 if key in test_set else 0)
    di = torch.tensor(di, device=device); si = torch.tensor(si, device=device)
    prob = torch.sigmoid(model.score(H, di, si)).cpu().numpy()
    return _metrics(np.array(y), prob, cfg.score_threshold)


def _metrics(y, prob, thr):
    pred = (prob >= thr).astype(int)
    return (
        roc_auc_score(y, prob),
        average_precision_score(y, prob),
        precision_score(y, pred, zero_division=0),
        recall_score(y, pred, zero_division=0),
        f1_score(y, pred, zero_division=0),
    )


def cross_validate(cfg: Config):
    torch.manual_seed(cfg.seed); np.random.seed(cfg.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    ds = BDataset(cfg)
    pos = ds.positives
    rng = np.random.default_rng(cfg.seed)
    perm = rng.permutation(len(pos))
    folds = np.array_split(perm, cfg.n_folds)

    rows = []
    for f in range(cfg.n_folds):
        test_idx = folds[f]
        train_idx = np.concatenate([folds[g] for g in range(cfg.n_folds) if g != f])
        res = run_fold(cfg, ds, pos[train_idx], pos[test_idx], device, rng)
        print(f"fold {f}: AUC={res[0]:.4f} AUPR={res[1]:.4f} "
              f"P={res[2]:.4f} R={res[3]:.4f} F1={res[4]:.4f}")
        rows.append(res)
    rows = np.array(rows)
    m, s = rows.mean(0), rows.std(0)
    print(f"\nMEAN  AUC={m[0]:.3f}±{s[0]:.3f}  AUPR={m[1]:.3f}±{s[1]:.3f}  "
          f"P={m[2]:.3f}  R={m[3]:.3f}  F1={m[4]:.3f}")
    return m, s

In [44]:
cross_validate(Config())

fold 0: AUC=0.8768 AUPR=0.8716 P=0.8199 R=0.7514 F1=0.7841
fold 1: AUC=0.8732 AUPR=0.8727 P=0.8144 R=0.7540 F1=0.7830
fold 2: AUC=0.8799 AUPR=0.8761 P=0.8234 R=0.7518 F1=0.7860
fold 3: AUC=0.8845 AUPR=0.8834 P=0.8247 R=0.7513 F1=0.7863
fold 4: AUC=0.8794 AUPR=0.8782 P=0.8191 R=0.7608 F1=0.7889

MEAN  AUC=0.879±0.004  AUPR=0.876±0.004  P=0.820  R=0.754  F1=0.786

(array([0.87875683, 0.87641199, 0.82028893, 0.75385548, 0.78565873]),
 array([0.00372953, 0.00420645, 0.00363346, 0.00360736, 0.00199811]))

In [ ]:
cross_validate(Config(sim_fusion="mean", 
                        recompute_gip=False, 
                        sim_topk=5, 
                        binarize_adj=True,
                        emb_dim=128,
                        dropout=0.2,
                        node_attn="gat",
                        predictor_hidden=128))

fold 0: AUC=0.8718 AUPR=0.8671 P=0.8083 R=0.7644 F1=0.7857
fold 1: AUC=0.8647 AUPR=0.8588 P=0.7951 R=0.7594 F1=0.7768
fold 2: AUC=0.8768 AUPR=0.8739 P=0.8075 R=0.7755 F1=0.7911
fold 3: AUC=0.8780 AUPR=0.8767 P=0.8407 R=0.7165 F1=0.7737
fold 4: AUC=0.8726 AUPR=0.8727 P=0.8025 R=0.7689 F1=0.7854

MEAN  AUC=0.873±0.005  AUPR=0.870±0.006  P=0.811  R=0.757  F1=0.783

(array([0.87279438, 0.86984736, 0.81079831, 0.75695007, 0.78254354]),
 array([0.00468582, 0.00634273, 0.01567995, 0.02088523, 0.00637257]))

In [ ]:
# Config(data_dir='/content/DRMGNE/data/B-dataset', n_drug=269, n_dis=598, n_prot=1021, sim_fusion='gip_fill', recompute_gip=False, sim_topk=15, sim_threshold=0.0, metapaths={1: ['RR', 'DD', 'PP', 'RD', 'RP', 'PD'], 2: ['RPR', 'RDR', 'DPD', 'RPD', 'RDP'], 3: ['RPDR', 'RDPD', 'RPRP']}, max_distance=3, binarize_adj=True, emb_dim=128, n_layers=1, dropout=0.2, residual=True, layernorm=True, node_attn='gat', predictor_hidden=128, neg_ratio=1, resample_neg_each_epoch=True, lr=0.001, weight_decay=0.0005, epochs=200, early_stop_patience=200, seed=42, n_folds=5, eval_mode='balanced', score_threshold=0.5)
cross_validate(Config(sim_fusion='gip_fill', recompute_gip=False, sim_topk=15, sim_threshold=0.0, binarize_adj=True, emb_dim=128, n_layers=1, dropout=0.2, residual=True, layernorm=True, node_attn='gat', predictor_hidden=128))

fold 0: AUC=0.8741 AUPR=0.8698 P=0.8172 R=0.7473 F1=0.7807
fold 1: AUC=0.8699 AUPR=0.8695 P=0.8098 R=0.7434 F1=0.7752
fold 2: AUC=0.8775 AUPR=0.8732 P=0.8128 R=0.7556 F1=0.7832
fold 3: AUC=0.8830 AUPR=0.8810 P=0.8142 R=0.7700 F1=0.7915
fold 4: AUC=0.8767 AUPR=0.8747 P=0.8117 R=0.7714 F1=0.7910

MEAN  AUC=0.876±0.004  AUPR=0.874±0.004  P=0.813  R=0.758  F1=0.784

(array([0.87623571, 0.87364487, 0.81314459, 0.75754834, 0.78431606]),
 array([0.00429646, 0.00415651, 0.0024707 , 0.01145203, 0.00624139]))

In [ ]:
# Config(data_dir='/content/DRMGNE/data/B-dataset', n_drug=269, n_dis=598, n_prot=1021, sim_fusion='gip_fill', recompute_gip=False, sim_topk=50, sim_threshold=0.0, metapaths={1: ['RR', 'DD', 'PP', 'RD', 'RP', 'PD'], 2: ['RPR', 'RDR', 'DPD', 'RPD', 'RDP'], 3: ['RPDR', 'RDPD', 'RPRP']}, max_distance=3, binarize_adj=True, emb_dim=128, n_layers=1, dropout=0.2, residual=True, layernorm=True, node_attn='paper', predictor_hidden=128, neg_ratio=1, resample_neg_each_epoch=True, lr=0.001, weight_decay=0.0005, epochs=200, early_stop_patience=200, seed=42, n_folds=5, eval_mode='balanced', score_threshold=0.5)
cross_validate(Config(sim_fusion='gip_fill', recompute_gip=False, sim_topk=50, binarize_adj=True, emb_dim=128, n_layers=1, dropout=0.2, node_attn='paper', predictor_hidden=128))

fold 0: AUC=0.8768 AUPR=0.8716 P=0.8199 R=0.7514 F1=0.7841
fold 1: AUC=0.8732 AUPR=0.8727 P=0.8144 R=0.7540 F1=0.7830
fold 2: AUC=0.8799 AUPR=0.8761 P=0.8234 R=0.7518 F1=0.7860
fold 3: AUC=0.8845 AUPR=0.8834 P=0.8247 R=0.7513 F1=0.7863
fold 4: AUC=0.8794 AUPR=0.8782 P=0.8191 R=0.7608 F1=0.7889

MEAN  AUC=0.879±0.004  AUPR=0.876±0.004  P=0.820  R=0.754  F1=0.786

(array([0.87875683, 0.87641199, 0.82028893, 0.75385548, 0.78565873]),
 array([0.00372953, 0.00420645, 0.00363346, 0.00360736, 0.00199811]))

In [45]:

# ================================================================
# P0 / P1 ENHANCEMENTS  (HANDOFF.md §5)
# ================================================================
# P0  - element-wise product decoder:  mul(h_drug, h_disease) -> MLP
# P1  - decoupled H0: similarity-only diagonal; association blocks = 0
#         (labels enter ONLY as meta-path graph edges, not node features)
# Fix - val-based model selection (hard rule §6.2);
#        dual protocol reporting (honest vs inflated);
#        balanced 1:1 AND imbalanced 1:5 AUPR (hard rule §6.5)
# ================================================================


# -- P0: element-wise product predictor -------------------------
class MPHAMv2(MPHAM):
    """Replaces concat-MLP with element-wise product MLP.
    mul(h_drug, h_disease) -> MLP -> logit  (DRMGNE / DistMult style).
    """
    def __init__(self, cfg, in_dim, n_distances):
        super().__init__(cfg, in_dim, n_distances)
        d = cfg.emb_dim
        # replace the 2*d->1 concat predictor with a d->1 mul predictor
        self.predictor = nn.Sequential(
            nn.Linear(d, cfg.predictor_hidden),
            nn.ReLU(),
            nn.Dropout(cfg.dropout),
            nn.Linear(cfg.predictor_hidden, 1),
        )

    def score(self, H, drug_idx, dis_idx):
        hr = H[drug_idx]
        hd = H[self.cfg.n_drug + dis_idx]
        return self.predictor(hr * hd).squeeze(-1)   # element-wise product


# -- P1: similarity-only H0 (no association off-diagonal blocks) -
def build_H0_decoupled(A_rd, A_rp, A_pd, S_rr, S_dd, S_pp):
    """H0 keeps only diagonal similarity blocks; association
    off-diagonals are zeroed.  Associations flow only through
    meta-path graph edges, never as raw node features.
    """
    nR, nD, nP = A_rd.shape[0], A_rd.shape[1], A_rp.shape[1]
    N = nR + nD + nP
    H0 = np.zeros((N, N), np.float32)
    H0[0:nR,         0:nR]         = S_rr
    H0[nR:nR+nD,     nR:nR+nD]     = S_dd
    H0[nR+nD:N,      nR+nD:N]      = S_pp
    return H0


# -- Revised fold runner with val-based model selection ----------
def run_fold_v2(cfg, ds, train_pos, test_pos, device, rng,
                decoder="mul", decouple=False, val_frac=0.1):
    """
    decoder   : "concat" = baseline MPHAM  |  "mul" = P0 MPHAMv2
    decouple  : False = coupled H0 (baseline)  |  True = P1 similarity-only H0
    val_frac  : fraction of train_pos withheld as validation for model selection

    Returns (h_bal, h_imb, i_bal, i_imb) -- each a 5-tuple (AUC,AUPR,P,R,F1):
        h_bal  honest,   balanced 1:1 eval
        h_imb  honest,   imbalanced 1:5 eval
        i_bal  inflated, balanced 1:1  (test-selection = paper/DRMGNE protocol)
        i_imb  inflated, imbalanced 1:5
    """
    nR, nD = cfg.n_drug, cfg.n_dis
    pos_set = set(map(int, ds.positives[:, 0] * nD + ds.positives[:, 1]))

    # -- val / train split ----------------------------------------
    n_val = max(1, int(len(train_pos) * val_frac))
    vidx  = rng.choice(len(train_pos), n_val, replace=False)
    vmask = np.ones(len(train_pos), dtype=bool); vmask[vidx] = False
    val_pos = train_pos[vidx]
    tr_pos  = train_pos[vmask]

    # -- leakage control: mask test edges from H0 and meta-paths --
    A_rd_tr = mask_test_edges(ds.A_rd, test_pos)
    S_rr, S_dd, S_pp = ds.build_similarities(A_rd_tr)
    H0_fn   = build_H0_decoupled if decouple else build_H0
    H0_np   = H0_fn(A_rd_tr, ds.A_rp, ds.A_pd, S_rr, S_dd, S_pp)
    adjs_np = build_metapath_adjs(cfg, A_rd_tr, ds.A_rp, ds.A_pd, S_rr, S_dd, S_pp)
    H0   = torch.from_numpy(H0_np).to(device)
    adjs = _adjs_to_torch(adjs_np, device)

    # -- model ----------------------------------------------------
    ModelCls = MPHAMv2 if decoder == "mul" else MPHAM
    model = ModelCls(cfg, in_dim=H0.shape[1], n_distances=len(adjs)).to(device)
    opt   = torch.optim.Adam(model.parameters(), lr=cfg.lr,
                              weight_decay=cfg.weight_decay)

    # -- fixed eval sets sampled once -----------------------------
    val_neg   = sample_negatives(pos_set, len(val_pos),      nR, nD, rng)
    test_neg1 = sample_negatives(pos_set, len(test_pos),     nR, nD, rng)  # 1:1
    test_neg5 = sample_negatives(pos_set, len(test_pos) * 5, nR, nD, rng)  # 1:5

    # init best states to initial weights (safety guard)
    best_val_auc  = -1; best_test_auc = -1; patience = 0
    best_state_val  = {k: v.clone() for k, v in model.state_dict().items()}
    best_state_test = {k: v.clone() for k, v in model.state_dict().items()}

    for epoch in range(cfg.epochs):
        model.train()
        if epoch == 0 or cfg.resample_neg_each_epoch:
            tr_neg = sample_negatives(pos_set, len(tr_pos) * cfg.neg_ratio, nR, nD, rng)
        pairs = np.vstack([tr_pos, tr_neg])
        yl    = np.concatenate([np.ones(len(tr_pos)),
                                np.zeros(len(tr_neg))]).astype(np.float32)
        di = torch.from_numpy(pairs[:, 0]).to(device)
        si = torch.from_numpy(pairs[:, 1]).to(device)
        y  = torch.from_numpy(yl).to(device)

        opt.zero_grad()
        H      = model.encode(H0, adjs)
        logits = model.score(H, di, si)
        loss   = F.binary_cross_entropy_with_logits(logits, y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        opt.step()

        # val-based selection (HONEST -- drives early stopping)
        vauc, *_ = evaluate(cfg, model, H0, adjs, val_pos, val_neg, device)
        if vauc > best_val_auc:
            best_val_auc = vauc; patience = 0
            best_state_val = {k: v.clone() for k, v in model.state_dict().items()}
        else:
            patience += 1
            if patience >= cfg.early_stop_patience: break

        # test-based selection (INFLATED -- record only, not used for stopping)
        tauc, *_ = evaluate(cfg, model, H0, adjs, test_pos, test_neg1, device)
        if tauc > best_test_auc:
            best_test_auc   = tauc
            best_state_test = {k: v.clone() for k, v in model.state_dict().items()}

    def _eval_both(state):
        model.load_state_dict(state)
        bal  = evaluate(cfg, model, H0, adjs, test_pos, test_neg1, device)
        imb5 = evaluate(cfg, model, H0, adjs, test_pos, test_neg5, device)
        return bal, imb5

    h_bal, h_imb = _eval_both(best_state_val)
    i_bal, i_imb = _eval_both(best_state_test)
    return h_bal, h_imb, i_bal, i_imb


def cross_validate_v2(cfg, decoder="mul", decouple=False, val_frac=0.1):
    """5-fold CV with val-based selection.
    Reports honest (val-selected) and inflated (test-selected) AUC/AUPR,
    plus 1:5 imbalanced AUPR for honest protocol.
    """
    torch.manual_seed(cfg.seed); np.random.seed(cfg.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"device={device}  decoder={decoder}  decouple={decouple}"
          f"  emb_dim={cfg.emb_dim}  node_attn={cfg.node_attn}"
          f"  epochs={cfg.epochs}")
    ds  = BDataset(cfg); pos = ds.positives
    rng = np.random.default_rng(cfg.seed)
    perm = rng.permutation(len(pos))
    folds = np.array_split(perm, cfg.n_folds)

    h_bal_rows = []; h_imb_rows = []
    i_bal_rows = []; i_imb_rows = []

    for f in range(cfg.n_folds):
        tidx  = folds[f]
        trinx = np.concatenate([folds[g] for g in range(cfg.n_folds) if g != f])
        h_bal, h_imb, i_bal, i_imb = run_fold_v2(
            cfg, ds, pos[trinx], pos[tidx], device, rng,
            decoder=decoder, decouple=decouple, val_frac=val_frac)
        print(f"  fold {f}:  "
              f"HONEST AUC={h_bal[0]:.4f} AUPR1={h_bal[1]:.4f} AUPR5={h_imb[1]:.4f}"
              f"  |  INFLATED AUC={i_bal[0]:.4f} AUPR1={i_bal[1]:.4f}")
        h_bal_rows.append(h_bal); h_imb_rows.append(h_imb)
        i_bal_rows.append(i_bal); i_imb_rows.append(i_imb)

    def _agg(rows, tag):
        a = np.array(rows); m, s = a.mean(0), a.std(0)
        print(f"  [{tag}] AUC={m[0]:.3f}+/-{s[0]:.3f}  AUPR={m[1]:.3f}+/-{s[1]:.3f}")
        return m, s

    print()
    hbm, hbs = _agg(h_bal_rows, "HONEST   bal 1:1")
    him, his = _agg(h_imb_rows, "HONEST   imb 1:5")
    ibm, ibs = _agg(i_bal_rows, "INFLATED bal 1:1")
    _agg(i_imb_rows,             "INFLATED imb 1:5")
    return (hbm, hbs), (him, his), (ibm, ibs)


print("P0/P1 classes and harness defined. Ready to run.")

P0/P1 classes and harness defined. Ready to run.

In [46]:

# -- P0: element-wise decoder, coupled H0, emb=128, gat ---------
# Hypothesis: element-wise product decoder alone gives the largest single gain.
# Baseline (cell 7): MEAN AUC=0.879+/-0.004  AUPR=0.876+/-0.004
print("=== P0: element-wise decoder, coupled H0 (emb=128, gat) ===")
p0_results = cross_validate_v2(
    Config(node_attn="gat"),
    decoder="mul",
    decouple=False,
)

=== P0: element-wise decoder, coupled H0 (emb=128, gat) ===
device=cuda  decoder=mul  decouple=False  emb_dim=128  node_attn=gat  epochs=200
  fold 0:  HONEST AUC=0.8734 AUPR1=0.8920 AUPR5=0.7215  |  INFLATED AUC=0.8918 AUPR1=0.8954
  fold 1:  HONEST AUC=0.8733 AUPR1=0.8925 AUPR5=0.7287  |  INFLATED AUC=0.8839 AUPR1=0.8850
  fold 2:  HONEST AUC=0.8741 AUPR1=0.8905 AUPR5=0.7206  |  INFLATED AUC=0.8895 AUPR1=0.8868
  fold 3:  HONEST AUC=0.8782 AUPR1=0.8954 AUPR5=0.7278  |  INFLATED AUC=0.8908 AUPR1=0.8929
  fold 4:  HONEST AUC=0.8738 AUPR1=0.8907 AUPR5=0.7213  |  INFLATED AUC=0.8941 AUPR1=0.8932

  [HONEST   bal 1:1] AUC=0.875+/-0.002  AUPR=0.892+/-0.002
  [HONEST   imb 1:5] AUC=0.875+/-0.001  AUPR=0.724+/-0.004
  [INFLATED bal 1:1] AUC=0.890+/-0.003  AUPR=0.891+/-0.004
  [INFLATED imb 1:5] AUC=0.891+/-0.003  AUPR=0.680+/-0.009

In [47]:

# -- P1: element-wise decoder + decoupled H0, emb=128, gat ------
# Hypothesis (DRMGNE evidence): decoupled features + mul decoder work jointly.
# Expected to push past 0.88-0.92 honest (HANDOFF.md §5, P1).
print("=== P1: element-wise decoder + decoupled H0 (emb=128, gat) ===")
p1_results = cross_validate_v2(
    Config(node_attn="gat"),
    decoder="mul",
    decouple=True,
)

=== P1: element-wise decoder + decoupled H0 (emb=128, gat) ===
device=cuda  decoder=mul  decouple=True  emb_dim=128  node_attn=gat  epochs=200
  fold 0:  HONEST AUC=0.9013 AUPR1=0.9155 AUPR5=0.7649  |  INFLATED AUC=0.9027 AUPR1=0.9154
  fold 1:  HONEST AUC=0.8923 AUPR1=0.8902 AUPR5=0.6905  |  INFLATED AUC=0.8976 AUPR1=0.9002
  fold 2:  HONEST AUC=0.9043 AUPR1=0.9083 AUPR5=0.7512  |  INFLATED AUC=0.9055 AUPR1=0.9106
  fold 3:  HONEST AUC=0.9052 AUPR1=0.9192 AUPR5=0.7574  |  INFLATED AUC=0.9052 AUPR1=0.9192
  fold 4:  HONEST AUC=0.9062 AUPR1=0.9152 AUPR5=0.7536  |  INFLATED AUC=0.9078 AUPR1=0.9178

  [HONEST   bal 1:1] AUC=0.902+/-0.005  AUPR=0.910+/-0.010
  [HONEST   imb 1:5] AUC=0.903+/-0.004  AUPR=0.744+/-0.027
  [INFLATED bal 1:1] AUC=0.904+/-0.003  AUPR=0.913+/-0.007
  [INFLATED imb 1:5] AUC=0.904+/-0.004  AUPR=0.750+/-0.016

In [48]:

# -- P0 emb=256: HANDOFF §8 recommended config ------------------
# Run P0 at larger embedding to check if capacity helps.
print("=== P0: element-wise decoder, emb=256, gat, coupled H0 ===")
p0_256_results = cross_validate_v2(
    Config(node_attn="gat", emb_dim=256, predictor_hidden=256),
    decoder="mul",
    decouple=False,
)

=== P0: element-wise decoder, emb=256, gat, coupled H0 ===
device=cuda  decoder=mul  decouple=False  emb_dim=256  node_attn=gat  epochs=200
  fold 0:  HONEST AUC=0.8833 AUPR1=0.9006 AUPR5=0.7474  |  INFLATED AUC=0.8944 AUPR1=0.8987
  fold 1:  HONEST AUC=0.8862 AUPR1=0.9032 AUPR5=0.7550  |  INFLATED AUC=0.8914 AUPR1=0.9018
  fold 2:  HONEST AUC=0.8944 AUPR1=0.9089 AUPR5=0.7591  |  INFLATED AUC=0.8967 AUPR1=0.8950
  fold 3:  HONEST AUC=0.8949 AUPR1=0.9114 AUPR5=0.7569  |  INFLATED AUC=0.8988 AUPR1=0.9144
  fold 4:  HONEST AUC=0.8901 AUPR1=0.9047 AUPR5=0.7534  |  INFLATED AUC=0.8954 AUPR1=0.8948

  [HONEST   bal 1:1] AUC=0.890+/-0.005  AUPR=0.906+/-0.004
  [HONEST   imb 1:5] AUC=0.890+/-0.003  AUPR=0.754+/-0.004
  [INFLATED bal 1:1] AUC=0.895+/-0.002  AUPR=0.901+/-0.007
  [INFLATED imb 1:5] AUC=0.895+/-0.003  AUPR=0.715+/-0.027

In [49]:

# ================================================================
# P5 — P1 + emb=256  (HANDOFF §7, quick win ~5 min)
# ================================================================
# Expected: ~0.005-0.01 AUC gain from P1 emb=128 (0.902 honest).
# P0 emb=256 gained +0.015 AUC over P0 emb=128 (0.890 vs 0.875).
print("=== P5: element-wise decoder + decoupled H0 + emb=256 ===")
p5_results = cross_validate_v2(
    Config(node_attn="gat", emb_dim=256, predictor_hidden=256),
    decoder="mul",
    decouple=True,
)

=== P5: element-wise decoder + decoupled H0 + emb=256 ===
device=cuda  decoder=mul  decouple=True  emb_dim=256  node_attn=gat  epochs=200
  fold 0:  HONEST AUC=0.9083 AUPR1=0.9235 AUPR5=0.7892  |  INFLATED AUC=0.9083 AUPR1=0.9235
  fold 1:  HONEST AUC=0.8965 AUPR1=0.8970 AUPR5=0.7032  |  INFLATED AUC=0.8992 AUPR1=0.9066
  fold 2:  HONEST AUC=0.9053 AUPR1=0.9101 AUPR5=0.7586  |  INFLATED AUC=0.9068 AUPR1=0.9207
  fold 3:  HONEST AUC=0.9061 AUPR1=0.9195 AUPR5=0.7731  |  INFLATED AUC=0.9066 AUPR1=0.9204
  fold 4:  HONEST AUC=0.9063 AUPR1=0.9162 AUPR5=0.7553  |  INFLATED AUC=0.9074 AUPR1=0.9141

  [HONEST   bal 1:1] AUC=0.905+/-0.004  AUPR=0.913+/-0.009
  [HONEST   imb 1:5] AUC=0.905+/-0.005  AUPR=0.756+/-0.029
  [INFLATED bal 1:1] AUC=0.906+/-0.003  AUPR=0.917+/-0.006
  [INFLATED imb 1:5] AUC=0.906+/-0.003  AUPR=0.768+/-0.023

In [50]:

# ================================================================
# P2 — k-NN sparsified meta-path adjacencies  (HANDOFF §7)
# ================================================================
# Extends Config with metapath_topk and rewrites build_metapath_adjs
# to apply row-wise top-k sparsification (rectangular-safe).
# Reduces over-smoothing from dense full-commuting adjacencies.

from dataclasses import dataclass, field
from typing import Dict, List

@dataclass
class Config:
    data_dir:   str = "/content/DRMGNE/data/B-dataset"
    n_drug:     int = N_DRUG
    n_dis:      int = N_DIS
    n_prot:     int = N_PROT
    sim_fusion: str = "gip_fill"
    recompute_gip: bool = False
    sim_topk:   int = 50
    sim_threshold: float = 0.0
    metapaths: Dict[int, List[str]] = field(default_factory=lambda: {
        1: ["RR", "DD", "PP", "RD", "RP", "PD"],
        2: ["RPR", "RDR", "DPD", "RPD", "RDP"],
        3: ["RPDR", "RDPD", "RPRP"],
    })
    max_distance:  int   = 3
    binarize_adj:  bool  = True
    emb_dim:       int   = 128
    n_layers:      int   = 1
    dropout:       float = 0.2
    residual:      bool  = True
    layernorm:     bool  = True
    node_attn:     str   = "paper"
    predictor_hidden: int = 128
    neg_ratio:     int   = 1
    resample_neg_each_epoch: bool = True
    lr:            float = 1e-3
    weight_decay:  float = 5e-4
    epochs:        int   = 200
    early_stop_patience: int = 200
    seed:          int   = 42
    n_folds:       int   = 5
    eval_mode:     str   = "balanced"
    score_threshold: float = 0.5
    metapath_topk: int   = 0  # 0=off; >0 keeps top-k neighbours per row per meta-path


def build_metapath_adjs(cfg, A_rd, A_rp, A_pd, S_rr, S_dd, S_pp):
    """Returns {distance: [(name, NxN adj)]}. When cfg.metapath_topk > 0,
    Applies row-wise top-k per commuting matrix (works for rectangular paths)."""
    nR, nD, nP = cfg.n_drug, cfg.n_dis, cfg.n_prot
    N = nR + nD + nP
    off = {"R": 0, "D": nR, "P": nR + nD}
    cnt = {"R": nR, "D": nD, "P": nP}
    blocks = _base_blocks(A_rd, A_rp, A_pd, S_rr, S_dd, S_pp)
    topk = getattr(cfg, "metapath_topk", 0)

    out = {}
    for dist, names in cfg.metapaths.items():
        if dist > cfg.max_distance:
            continue
        lst = []
        for name in names:
            M = _metapath_commuting(name, blocks)
            if topk > 0:
                # Row-wise top-k: works for square AND rectangular M
                M = M.copy()
                for _i in range(M.shape[0]):
                    _row = M[_i]
                    if (_row > 0).sum() > topk:
                        _kth = np.partition(_row, -topk)[-topk]
                        M[_i, M[_i] < _kth] = 0.0
            s_type, e_type = name[0], name[-1]
            A = np.zeros((N, N), np.float32)
            rs = slice(off[s_type], off[s_type] + cnt[s_type])
            cs = slice(off[e_type], off[e_type] + cnt[e_type])
            A[rs, cs] = M
            A = np.maximum(A, A.T)
            if cfg.binarize_adj:
                A = (A > 0).astype(np.float32)
            else:
                deg = A.sum(1, keepdims=True); deg[deg == 0] = 1.0
                A = A / deg
            np.fill_diagonal(A, 1.0)
            lst.append((name, A))
        out[dist] = lst
    return out


print("Config extended with metapath_topk; build_metapath_adjs updated.")
print("=== P2a: P1 + k-NN meta-paths, topk=10, emb=128, gat ===")
p2a_results = cross_validate_v2(
    Config(node_attn="gat", metapath_topk=10),
    decoder="mul", decouple=True,
)
print("\n=== P2b: P1 + k-NN meta-paths, topk=10, emb=256, gat ===")
p2b_results = cross_validate_v2(
    Config(node_attn="gat", metapath_topk=10, emb_dim=256, predictor_hidden=256),
    decoder="mul", decouple=True,
)

Config extended with metapath_topk; build_metapath_adjs updated.
=== P2a: P1 + k-NN meta-paths, topk=10, emb=128, gat ===
device=cuda  decoder=mul  decouple=True  emb_dim=128  node_attn=gat  epochs=200
  fold 0:  HONEST AUC=0.9035 AUPR1=0.9167 AUPR5=0.7663  |  INFLATED AUC=0.9035 AUPR1=0.9167
  fold 1:  HONEST AUC=0.8968 AUPR1=0.9006 AUPR5=0.7152  |  INFLATED AUC=0.8977 AUPR1=0.9004
  fold 2:  HONEST AUC=0.9034 AUPR1=0.9110 AUPR5=0.7598  |  INFLATED AUC=0.9050 AUPR1=0.9158
  fold 3:  HONEST AUC=0.9066 AUPR1=0.9217 AUPR5=0.7785  |  INFLATED AUC=0.9066 AUPR1=0.9217
  fold 4:  HONEST AUC=0.9074 AUPR1=0.9165 AUPR5=0.7565  |  INFLATED AUC=0.9075 AUPR1=0.9174

  [HONEST   bal 1:1] AUC=0.904+/-0.004  AUPR=0.913+/-0.007
  [HONEST   imb 1:5] AUC=0.904+/-0.003  AUPR=0.755+/-0.021
  [INFLATED bal 1:1] AUC=0.904+/-0.003  AUPR=0.914+/-0.007
  [INFLATED imb 1:5] AUC=0.904+/-0.003  AUPR=0.759+/-0.023

=== P2b: P1 + k-NN meta-paths, topk=10, emb=256, gat ===
device=cuda  decoder=mul  decouple=True  emb_dim=256  node_attn=gat  epochs=200
  fold 0:  HONEST AUC=0.9095 AUPR1=0.9244 AUPR5=0.7925  |  INFLATED AUC=0.9110 AUPR1=0.9270
  fold 1:  HONEST AUC=0.9024 AUPR1=0.9116 AUPR5=0.7564  |  INFLATED AUC=0.9024 AUPR1=0.9116
  fold 2:  HONEST AUC=0.9063 AUPR1=0.9207 AUPR5=0.7948  |  INFLATED AUC=0.9087 AUPR1=0.9214
  fold 3:  HONEST AUC=0.9058 AUPR1=0.9231 AUPR5=0.7964  |  INFLATED AUC=0.9088 AUPR1=0.9194
  fold 4:  HONEST AUC=0.9101 AUPR1=0.9248 AUPR5=0.7916  |  INFLATED AUC=0.9103 AUPR1=0.9252

  [HONEST   bal 1:1] AUC=0.907+/-0.003  AUPR=0.921+/-0.005
  [HONEST   imb 1:5] AUC=0.908+/-0.002  AUPR=0.786+/-0.015
  [INFLATED bal 1:1] AUC=0.908+/-0.003  AUPR=0.921+/-0.005
  [INFLATED imb 1:5] AUC=0.909+/-0.002  AUPR=0.780+/-0.016

In [51]:

# ================================================================
# P3 — Hard-negative enhancement  (HANDOFF §7, DRMGNE port)
# ================================================================
# After each epoch's forward pass, synthesises hard negatives by
# interpolating positive and negative disease embeddings:
#   mix_score = mean(h_dis_pos * h_dis_neg).detach()  [detach scalar]
#   h_dis_hard = mix_score * h_dis_pos + (1-mix_score) * h_dis_neg
# Adds an auxiliary BCE term weighted by hard_neg_weight.
# Assumes P2 cell has been run (build_metapath_adjs with topk support).

import torch.nn.functional as F

def run_fold_v3(cfg, ds, train_pos, test_pos, device, rng,
                decoder="mul", decouple=True, val_frac=0.1,
                hard_neg_weight=0.5):
    nR, nD = cfg.n_drug, cfg.n_dis
    pos_set = set(map(int, ds.positives[:, 0] * nD + ds.positives[:, 1]))

    n_val = max(1, int(len(train_pos) * val_frac))
    vidx  = rng.choice(len(train_pos), n_val, replace=False)
    vmask = np.ones(len(train_pos), dtype=bool); vmask[vidx] = False
    val_pos = train_pos[vidx]; tr_pos = train_pos[vmask]

    A_rd_tr = mask_test_edges(ds.A_rd, test_pos)
    S_rr, S_dd, S_pp = ds.build_similarities(A_rd_tr)
    H0_fn  = build_H0_decoupled if decouple else build_H0
    H0_np  = H0_fn(A_rd_tr, ds.A_rp, ds.A_pd, S_rr, S_dd, S_pp)
    adjs_np = build_metapath_adjs(cfg, A_rd_tr, ds.A_rp, ds.A_pd, S_rr, S_dd, S_pp)
    H0   = torch.from_numpy(H0_np).to(device)
    adjs = _adjs_to_torch(adjs_np, device)

    ModelCls = MPHAMv2 if decoder == "mul" else MPHAM
    model = ModelCls(cfg, in_dim=H0.shape[1], n_distances=len(adjs)).to(device)
    opt   = torch.optim.Adam(model.parameters(), lr=cfg.lr,
                              weight_decay=cfg.weight_decay)

    val_neg   = sample_negatives(pos_set, len(val_pos),      nR, nD, rng)
    test_neg1 = sample_negatives(pos_set, len(test_pos),     nR, nD, rng)
    test_neg5 = sample_negatives(pos_set, len(test_pos) * 5, nR, nD, rng)

    best_val_auc = -1; best_test_auc = -1; patience = 0
    best_state_val  = {k: v.clone() for k, v in model.state_dict().items()}
    best_state_test = {k: v.clone() for k, v in model.state_dict().items()}

    for epoch in range(cfg.epochs):
        model.train()
        if epoch == 0 or cfg.resample_neg_each_epoch:
            tr_neg = sample_negatives(pos_set, len(tr_pos) * cfg.neg_ratio, nR, nD, rng)

        pos_di = torch.from_numpy(tr_pos[:, 0]).to(device)
        pos_si = torch.from_numpy(tr_pos[:, 1]).to(device)
        neg_di = torch.from_numpy(tr_neg[:, 0]).to(device)
        neg_si = torch.from_numpy(tr_neg[:, 1]).to(device)

        opt.zero_grad()
        H = model.encode(H0, adjs)

        h_drug_pos = H[pos_di]
        h_dis_pos  = H[nR + pos_si]
        h_drug_neg = H[neg_di]
        h_dis_neg  = H[nR + neg_si]

        # base BCE loss
        logits_pos = model.predictor(h_drug_pos * h_dis_pos).squeeze(-1)
        logits_neg = model.predictor(h_drug_neg * h_dis_neg).squeeze(-1)
        loss = F.binary_cross_entropy_with_logits(
            torch.cat([logits_pos, logits_neg]),
            torch.cat([torch.ones(len(pos_di), device=device),
                       torch.zeros(len(neg_di), device=device)]))

        # hard-negative enhancement (DRMGNE negative_enhance)
        n_mix = min(len(h_dis_pos), len(h_dis_neg))
        mix_score = torch.mean(h_dis_pos[:n_mix] * h_dis_neg[:n_mix]).detach()
        h_dis_hard = mix_score * h_dis_pos[:n_mix] + (1.0 - mix_score) * h_dis_neg[:n_mix]
        logits_hard = model.predictor(h_drug_neg[:n_mix] * h_dis_hard).squeeze(-1)
        loss_hard = F.binary_cross_entropy_with_logits(
            logits_hard, torch.zeros(n_mix, device=device))
        loss = loss + hard_neg_weight * loss_hard

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        opt.step()

        vauc, *_ = evaluate(cfg, model, H0, adjs, val_pos, val_neg, device)
        if vauc > best_val_auc:
            best_val_auc = vauc; patience = 0
            best_state_val = {k: v.clone() for k, v in model.state_dict().items()}
        else:
            patience += 1
            if patience >= cfg.early_stop_patience: break

        tauc, *_ = evaluate(cfg, model, H0, adjs, test_pos, test_neg1, device)
        if tauc > best_test_auc:
            best_test_auc = tauc
            best_state_test = {k: v.clone() for k, v in model.state_dict().items()}

    def _eval_both(state):
        model.load_state_dict(state)
        bal  = evaluate(cfg, model, H0, adjs, test_pos, test_neg1, device)
        imb5 = evaluate(cfg, model, H0, adjs, test_pos, test_neg5, device)
        return bal, imb5

    h_bal, h_imb = _eval_both(best_state_val)
    i_bal, i_imb = _eval_both(best_state_test)
    return h_bal, h_imb, i_bal, i_imb


def cross_validate_v3(cfg, decoder="mul", decouple=True,
                      val_frac=0.1, hard_neg_weight=0.5):
    torch.manual_seed(cfg.seed); np.random.seed(cfg.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"device={device}  decoder={decoder}  decouple={decouple}"
          f"  emb_dim={cfg.emb_dim}  node_attn={cfg.node_attn}"
          f"  metapath_topk={getattr(cfg,'metapath_topk',0)}"
          f"  hard_neg_weight={hard_neg_weight}  epochs={cfg.epochs}")
    ds  = BDataset(cfg); pos = ds.positives
    rng = np.random.default_rng(cfg.seed)
    perm = rng.permutation(len(pos)); folds = np.array_split(perm, cfg.n_folds)

    h_bal_rows=[]; h_imb_rows=[]; i_bal_rows=[]; i_imb_rows=[]
    for f in range(cfg.n_folds):
        tidx  = folds[f]
        trinx = np.concatenate([folds[g] for g in range(cfg.n_folds) if g != f])
        h_bal, h_imb, i_bal, i_imb = run_fold_v3(
            cfg, ds, pos[trinx], pos[tidx], device, rng,
            decoder=decoder, decouple=decouple, val_frac=val_frac,
            hard_neg_weight=hard_neg_weight)
        print(f"  fold {f}:  "
              f"HONEST AUC={h_bal[0]:.4f} AUPR1={h_bal[1]:.4f} AUPR5={h_imb[1]:.4f}"
              f"  |  INFLATED AUC={i_bal[0]:.4f} AUPR1={i_bal[1]:.4f}")
        h_bal_rows.append(h_bal); h_imb_rows.append(h_imb)
        i_bal_rows.append(i_bal); i_imb_rows.append(i_imb)

    def _agg(rows, tag):
        a = np.array(rows); m, s = a.mean(0), a.std(0)
        print(f"  [{tag}] AUC={m[0]:.3f}+/-{s[0]:.3f}  AUPR={m[1]:.3f}+/-{s[1]:.3f}")
        return m, s

    print()
    hbm, hbs = _agg(h_bal_rows, "HONEST   bal 1:1")
    him, his = _agg(h_imb_rows, "HONEST   imb 1:5")
    ibm, ibs = _agg(i_bal_rows, "INFLATED bal 1:1")
    _agg(i_imb_rows,             "INFLATED imb 1:5")
    return (hbm, hbs), (him, his), (ibm, ibs)


print("P3 run_fold_v3 / cross_validate_v3 defined.")
print("=== P3: P1+P2 + hard negatives (topk=10, emb=128, hard_neg=0.5) ===")
p3_results = cross_validate_v3(
    Config(node_attn="gat", metapath_topk=10),
    decoder="mul", decouple=True,
)

print("P3 run_fold_v3 / cross_validate_v3 defined.")
print("=== P3: P1+P2 + hard negatives (topk=10, emb=256, hard_neg=0.5) ===")
p3_results = cross_validate_v3(
    Config(node_attn="gat", metapath_topk=10, emb_dim=256, predictor_hidden=256),
    decoder="mul", decouple=True,
)

P3 run_fold_v3 / cross_validate_v3 defined.
=== P3: P1+P2 + hard negatives (topk=10, emb=128, hard_neg=0.5) ===
device=cuda  decoder=mul  decouple=True  emb_dim=128  node_attn=gat  metapath_topk=10  hard_neg_weight=0.5  epochs=200
  fold 0:  HONEST AUC=0.9037 AUPR1=0.9158 AUPR5=0.7647  |  INFLATED AUC=0.9037 AUPR1=0.9158
  fold 1:  HONEST AUC=0.8972 AUPR1=0.8986 AUPR5=0.7115  |  INFLATED AUC=0.8972 AUPR1=0.8986
  fold 2:  HONEST AUC=0.9002 AUPR1=0.9016 AUPR5=0.7312  |  INFLATED AUC=0.9062 AUPR1=0.9159
  fold 3:  HONEST AUC=0.9045 AUPR1=0.9164 AUPR5=0.7536  |  INFLATED AUC=0.9049 AUPR1=0.9166
  fold 4:  HONEST AUC=0.9072 AUPR1=0.9205 AUPR5=0.7660  |  INFLATED AUC=0.9080 AUPR1=0.9189

  [HONEST   bal 1:1] AUC=0.903+/-0.003  AUPR=0.911+/-0.009
  [HONEST   imb 1:5] AUC=0.903+/-0.002  AUPR=0.745+/-0.021
  [INFLATED bal 1:1] AUC=0.904+/-0.004  AUPR=0.913+/-0.007
  [INFLATED imb 1:5] AUC=0.904+/-0.003  AUPR=0.749+/-0.020
P3 run_fold_v3 / cross_validate_v3 defined.
=== P3: P1+P2 + hard negatives (topk=10, emb=256, hard_neg=0.5) ===
device=cuda  decoder=mul  decouple=True  emb_dim=256  node_attn=gat  metapath_topk=10  hard_neg_weight=0.5  epochs=200
  fold 0:  HONEST AUC=0.9132 AUPR1=0.9248 AUPR5=0.7876  |  INFLATED AUC=0.9132 AUPR1=0.9245
  fold 1:  HONEST AUC=0.9022 AUPR1=0.9091 AUPR5=0.7495  |  INFLATED AUC=0.9024 AUPR1=0.9123
  fold 2:  HONEST AUC=0.9089 AUPR1=0.9182 AUPR5=0.7771  |  INFLATED AUC=0.9111 AUPR1=0.9220
  fold 3:  HONEST AUC=0.9078 AUPR1=0.9229 AUPR5=0.7867  |  INFLATED AUC=0.9094 AUPR1=0.9258
  fold 4:  HONEST AUC=0.9108 AUPR1=0.9253 AUPR5=0.7852  |  INFLATED AUC=0.9121 AUPR1=0.9249

  [HONEST   bal 1:1] AUC=0.909+/-0.004  AUPR=0.920+/-0.006
  [HONEST   imb 1:5] AUC=0.909+/-0.003  AUPR=0.777+/-0.014
  [INFLATED bal 1:1] AUC=0.910+/-0.004  AUPR=0.922+/-0.005
  [INFLATED imb 1:5] AUC=0.910+/-0.003  AUPR=0.782+/-0.014

In [52]:

# ================================================================
# P4 — MF-hybrid: free latent factors + MPHAM encoder  (HANDOFF §7)
# ================================================================
# MPHAMv4 adds u_drug (n_drug, emb_dim) and u_dis (n_dis, emb_dim).
#   h_drug_final = h_gnn[i] + u_drug[i]    (residual MF addition)
#   h_dis_final  = h_gnn[j] + u_dis[j]
#   score = MLP(h_drug_final * h_dis_final)
# Latent factors initialised to 0 so GNN dominates at start.
# Separate higher weight-decay (1e-2) for latent factors to regularise MF.
# Needs ~400 epochs to converge; set epochs=400, early_stop_patience=400.
# Ablation (pure MF): temporarily zero out H before passing to score().

import torch
import torch.nn as nn
import torch.nn.functional as F

class MPHAMv4(MPHAMv2):
    """P4: GNN encoder + additive free latent factors (MF-hybrid)."""
    def __init__(self, cfg, in_dim, n_distances):
        super().__init__(cfg, in_dim, n_distances)
        d = cfg.emb_dim
        self.u_drug = nn.Embedding(cfg.n_drug, d)
        self.u_dis  = nn.Embedding(cfg.n_dis,  d)
        nn.init.zeros_(self.u_drug.weight)   # GNN dominates at init
        nn.init.zeros_(self.u_dis.weight)

    def score(self, H, drug_idx, dis_idx):
        nR = self.cfg.n_drug
        hr = H[drug_idx]     + self.u_drug(drug_idx)
        hd = H[nR + dis_idx] + self.u_dis(dis_idx)
        return self.predictor(hr * hd).squeeze(-1)


def run_fold_v4(cfg, ds, train_pos, test_pos, device, rng,
                decouple=True, val_frac=0.1):
    """P4 fold runner: MPHAMv4 with separate high weight-decay for latent factors."""
    nR, nD = cfg.n_drug, cfg.n_dis
    pos_set = set(map(int, ds.positives[:, 0] * nD + ds.positives[:, 1]))

    n_val = max(1, int(len(train_pos) * val_frac))
    vidx  = rng.choice(len(train_pos), n_val, replace=False)
    vmask = np.ones(len(train_pos), dtype=bool); vmask[vidx] = False
    val_pos = train_pos[vidx]; tr_pos = train_pos[vmask]

    A_rd_tr = mask_test_edges(ds.A_rd, test_pos)
    S_rr, S_dd, S_pp = ds.build_similarities(A_rd_tr)
    H0_fn  = build_H0_decoupled if decouple else build_H0
    H0_np  = H0_fn(A_rd_tr, ds.A_rp, ds.A_pd, S_rr, S_dd, S_pp)
    adjs_np = build_metapath_adjs(cfg, A_rd_tr, ds.A_rp, ds.A_pd, S_rr, S_dd, S_pp)
    H0   = torch.from_numpy(H0_np).to(device)
    adjs = _adjs_to_torch(adjs_np, device)

    model = MPHAMv4(cfg, in_dim=H0.shape[1], n_distances=len(adjs)).to(device)

    # Separate weight-decay: GNN params = cfg.weight_decay, MF params = 1e-2
    gnn_params = [p for n, p in model.named_parameters()
                  if "u_drug" not in n and "u_dis" not in n]
    mf_params  = list(model.u_drug.parameters()) + list(model.u_dis.parameters())
    opt = torch.optim.Adam([
        {"params": gnn_params, "weight_decay": cfg.weight_decay},
        {"params": mf_params,  "weight_decay": 1e-2},
    ], lr=cfg.lr)

    val_neg   = sample_negatives(pos_set, len(val_pos),      nR, nD, rng)
    test_neg1 = sample_negatives(pos_set, len(test_pos),     nR, nD, rng)
    test_neg5 = sample_negatives(pos_set, len(test_pos) * 5, nR, nD, rng)

    best_val_auc = -1; best_test_auc = -1; patience = 0
    best_state_val  = {k: v.clone() for k, v in model.state_dict().items()}
    best_state_test = {k: v.clone() for k, v in model.state_dict().items()}

    for epoch in range(cfg.epochs):
        model.train()
        if epoch == 0 or cfg.resample_neg_each_epoch:
            tr_neg = sample_negatives(pos_set, len(tr_pos) * cfg.neg_ratio, nR, nD, rng)
        pairs = np.vstack([tr_pos, tr_neg])
        yl    = np.concatenate([np.ones(len(tr_pos)),
                                np.zeros(len(tr_neg))]).astype(np.float32)
        di = torch.from_numpy(pairs[:, 0]).to(device)
        si = torch.from_numpy(pairs[:, 1]).to(device)
        y  = torch.from_numpy(yl).to(device)

        opt.zero_grad()
        H      = model.encode(H0, adjs)
        logits = model.score(H, di, si)
        loss   = F.binary_cross_entropy_with_logits(logits, y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        opt.step()

        vauc, *_ = evaluate(cfg, model, H0, adjs, val_pos, val_neg, device)
        if vauc > best_val_auc:
            best_val_auc = vauc; patience = 0
            best_state_val = {k: v.clone() for k, v in model.state_dict().items()}
        else:
            patience += 1
            if patience >= cfg.early_stop_patience: break

        tauc, *_ = evaluate(cfg, model, H0, adjs, test_pos, test_neg1, device)
        if tauc > best_test_auc:
            best_test_auc = tauc
            best_state_test = {k: v.clone() for k, v in model.state_dict().items()}

    def _eval_both(state):
        model.load_state_dict(state)
        bal  = evaluate(cfg, model, H0, adjs, test_pos, test_neg1, device)
        imb5 = evaluate(cfg, model, H0, adjs, test_pos, test_neg5, device)
        return bal, imb5

    h_bal, h_imb = _eval_both(best_state_val)
    i_bal, i_imb = _eval_both(best_state_test)
    return h_bal, h_imb, i_bal, i_imb


def cross_validate_v4(cfg, decouple=True, val_frac=0.1):
    torch.manual_seed(cfg.seed); np.random.seed(cfg.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"device={device}  decouple={decouple}  emb_dim={cfg.emb_dim}"
          f"  node_attn={cfg.node_attn}"
          f"  metapath_topk={getattr(cfg,'metapath_topk',0)}"
          f"  epochs={cfg.epochs}  (MF latent factors enabled)")
    ds  = BDataset(cfg); pos = ds.positives
    rng = np.random.default_rng(cfg.seed)
    perm = rng.permutation(len(pos)); folds = np.array_split(perm, cfg.n_folds)

    h_bal_rows=[]; h_imb_rows=[]; i_bal_rows=[]; i_imb_rows=[]
    for f in range(cfg.n_folds):
        tidx  = folds[f]
        trinx = np.concatenate([folds[g] for g in range(cfg.n_folds) if g != f])
        h_bal, h_imb, i_bal, i_imb = run_fold_v4(
            cfg, ds, pos[trinx], pos[tidx], device, rng,
            decouple=decouple, val_frac=val_frac)
        print(f"  fold {f}:  "
              f"HONEST AUC={h_bal[0]:.4f} AUPR1={h_bal[1]:.4f} AUPR5={h_imb[1]:.4f}"
              f"  |  INFLATED AUC={i_bal[0]:.4f} AUPR1={i_bal[1]:.4f}")
        h_bal_rows.append(h_bal); h_imb_rows.append(h_imb)
        i_bal_rows.append(i_bal); i_imb_rows.append(i_imb)

    def _agg(rows, tag):
        a = np.array(rows); m, s = a.mean(0), a.std(0)
        print(f"  [{tag}] AUC={m[0]:.3f}+/-{s[0]:.3f}  AUPR={m[1]:.3f}+/-{s[1]:.3f}")
        return m, s

    print()
    hbm, hbs = _agg(h_bal_rows, "HONEST   bal 1:1")
    him, his = _agg(h_imb_rows, "HONEST   imb 1:5")
    ibm, ibs = _agg(i_bal_rows, "INFLATED bal 1:1")
    _agg(i_imb_rows,             "INFLATED imb 1:5")
    return (hbm, hbs), (him, his), (ibm, ibs)


print("P4 MPHAMv4 / run_fold_v4 / cross_validate_v4 defined.")
print("=== P4: MF-hybrid, topk=10, emb=128, 400 epochs ===")
p4_results = cross_validate_v4(
    Config(node_attn="gat", metapath_topk=10,
           epochs=400, early_stop_patience=400),
    decouple=True,
)

print("P4 MPHAMv4 / run_fold_v4 / cross_validate_v4 defined.")
print("=== P4: MF-hybrid, topk=10, emb=256, 400 epochs ===")
p4_results = cross_validate_v4(
    Config(node_attn="gat", metapath_topk=10,
           epochs=400, early_stop_patience=400,
           emb_dim=256, predictor_hidden=256),
    decouple=True,
)

P4 MPHAMv4 / run_fold_v4 / cross_validate_v4 defined.
=== P4: MF-hybrid, topk=10, emb=128, 400 epochs ===
device=cuda  decouple=True  emb_dim=128  node_attn=gat  metapath_topk=10  epochs=400  (MF latent factors enabled)
  fold 0:  HONEST AUC=0.9042 AUPR1=0.9203 AUPR5=0.7802  |  INFLATED AUC=0.9049 AUPR1=0.9214
  fold 1:  HONEST AUC=0.8934 AUPR1=0.9021 AUPR5=0.7338  |  INFLATED AUC=0.8960 AUPR1=0.9128
  fold 2:  HONEST AUC=0.9011 AUPR1=0.9186 AUPR5=0.7972  |  INFLATED AUC=0.9027 AUPR1=0.9136
  fold 3:  HONEST AUC=0.9043 AUPR1=0.9122 AUPR5=0.7588  |  INFLATED AUC=0.9060 AUPR1=0.9191
  fold 4:  HONEST AUC=0.9036 AUPR1=0.9159 AUPR5=0.7693  |  INFLATED AUC=0.9042 AUPR1=0.9222

  [HONEST   bal 1:1] AUC=0.901+/-0.004  AUPR=0.914+/-0.006
  [HONEST   imb 1:5] AUC=0.903+/-0.002  AUPR=0.768+/-0.021
  [INFLATED bal 1:1] AUC=0.903+/-0.004  AUPR=0.918+/-0.004
  [INFLATED imb 1:5] AUC=0.904+/-0.003  AUPR=0.779+/-0.014
P4 MPHAMv4 / run_fold_v4 / cross_validate_v4 defined.
=== P4: MF-hybrid, topk=10, emb=256, 400 epochs ===
device=cuda  decouple=True  emb_dim=256  node_attn=gat  metapath_topk=10  epochs=400  (MF latent factors enabled)
  fold 0:  HONEST AUC=0.9115 AUPR1=0.9263 AUPR5=0.7950  |  INFLATED AUC=0.9115 AUPR1=0.9263
  fold 1:  HONEST AUC=0.9040 AUPR1=0.9212 AUPR5=0.7954  |  INFLATED AUC=0.9047 AUPR1=0.9170
  fold 2:  HONEST AUC=0.9036 AUPR1=0.9236 AUPR5=0.8155  |  INFLATED AUC=0.9064 AUPR1=0.9223
  fold 3:  HONEST AUC=0.9072 AUPR1=0.9226 AUPR5=0.7930  |  INFLATED AUC=0.9113 AUPR1=0.9216
  fold 4:  HONEST AUC=0.9083 AUPR1=0.9203 AUPR5=0.7716  |  INFLATED AUC=0.9085 AUPR1=0.9230

  [HONEST   bal 1:1] AUC=0.907+/-0.003  AUPR=0.923+/-0.002
  [HONEST   imb 1:5] AUC=0.907+/-0.001  AUPR=0.794+/-0.014
  [INFLATED bal 1:1] AUC=0.908+/-0.003  AUPR=0.922+/-0.003
  [INFLATED imb 1:5] AUC=0.909+/-0.001  AUPR=0.786+/-0.012